# Generated by Django 5.2.1 on 2025-12-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='posts/'),
        ),
    ]
